# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='container',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='externalservice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='host',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
