# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='host',
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ManyToManyField(blank=True, to='assets.Group', verbose_name='所属组'),
        ),
    ]
