# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20170718_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parent_group',
        ),
        migrations.AddField(
            model_name='group',
            name='children_groups',
            field=models.ManyToManyField(blank=True, to='assets.Group', verbose_name='子组'),
        ),
    ]
